function [T, metadata] = frozen_gray_pam8_relation()
%FROZEN_GRAY_PAM8_RELATION Versioned matrix from the user-verified search.
% Column convention: canonical Gray label b = T*z mod 2.
    T = [0 0 1; 1 0 0; 1 1 0];
    metadata = struct('version', 'pam8-gf2-v1-20260828', ...
        'lambda_axis', [-0.5 -0.25 0 0.25 0.5], ...
        'candidate_count', 168, 'mean_kl_reported', 2.521e-3, ...
        'max_kl_reported', 0.0067, ...
        'metrics_precision', 'rounded user MATLAB console output', ...
        'p_by_lambda_status', 'not captured');
end
